version: 2

docker_login: &docker_login
  run:
    name: authentication
    command: |
      docker --version
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

workflows:
  version: 2
  flow:
    jobs:
      - musl_build
      #- unit_test
      - docker_push:
          requires:
            - musl_build
          filters:
            branches:
              only:
                - master
jobs:
  musl_build:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - cargo.registry.release-{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          keys:
          - target.release-{{ .Environment.CACHE_VERSION }}
      - run: cargo build --release
      - save_cache:
          key: target.release-{{ .Environment.CACHE_VERSION }}
          paths:
            - target
      - save_cache:
          key: cargo.registry.release-{{ .Environment.CACHE_VERSION }}
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - controller

  unit_test:
    docker:
      - image: clux/muslrust:stable
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - cargo.registry.debug-{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          keys:
          - target.debug-{{ .Environment.CACHE_VERSION }}
      - run: cargo test
      - run: cargo doc --no-deps
      - save_cache:
          key: target.debug-{{ .Environment.CACHE_VERSION }}
          paths:
            - target
      - save_cache:
          key: cargo.registry.debug-{{ .Environment.CACHE_VERSION }}
          paths:
            - /root/.cargo

  docker_push:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - <<: *docker_login
      - run: make tag-latest
      - run: make tag-semver
