---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foobar
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: foobar
rules:
- apiGroups: ["clux.dev"]
  resources:
  - foos
  verbs: ["list", "get", "watch", "create", "delete", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: foobbar-view
subjects:
- kind: ServiceAccount
  name: foobar
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: foobar
